train:
  # Directory in which model checkpoints & summaries (for Tensorboard) will be saved
  job_dir: jobs/
  debug: True
  image_vis: train

eval:
  image_vis: eval

dataset:
  type: tfrecord
  # From which directory to read the dataset
  dir: datasets/voc/tf

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict
    num_classes: 20

  base_network:
    # Which type of pretrained network to use
    # Should we train the pretrained network
    trainable: True
    # Should we download weights if not available
    download: True
